In [1]:
import numpy as np

In [2]:
x1 = np.array([1,2,3,4])
print(x1)
print(x1.shape)
print(x1.ndim)
print(type(x1))

[1 2 3 4]
(4,)
1
<class 'numpy.ndarray'>


In [3]:
x2 = np.array([
    [1,2,3],
    [4,5,6]
])
print(x2)
print(x2.shape)
print(x2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [4]:
a = np.arange(10, 51, .5)
print(a)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5 23.  23.5
 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5 30.  30.5
 31.  31.5 32.  32.5 33.  33.5 34.  34.5 35.  35.5 36.  36.5 37.  37.5
 38.  38.5 39.  39.5 40.  40.5 41.  41.5 42.  42.5 43.  43.5 44.  44.5
 45.  45.5 46.  46.5 47.  47.5 48.  48.5 49.  49.5 50.  50.5]


In [5]:
b = np.linspace(10,15, 25)
print(b)

[10.         10.20833333 10.41666667 10.625      10.83333333 11.04166667
 11.25       11.45833333 11.66666667 11.875      12.08333333 12.29166667
 12.5        12.70833333 12.91666667 13.125      13.33333333 13.54166667
 13.75       13.95833333 14.16666667 14.375      14.58333333 14.79166667
 15.        ]


In [6]:
c = np.random.randint(-10,10, (5,5))
print(c)

[[  4  -6   0  -2 -10]
 [  8  -4   2  -4  -1]
 [  7   9   8 -10  -4]
 [ -3   2   5   2   3]
 [  1   4   5   7  -9]]


In [7]:
x = np.linspace(10,99, 100).reshape(10,10).astype(int)
x

array([[10, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
       [27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [54, 55, 56, 57, 58, 59, 60, 61, 62, 63],
       [63, 64, 65, 66, 67, 68, 69, 70, 71, 72],
       [72, 73, 74, 75, 76, 77, 78, 79, 80, 81],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [8]:
print(x[0, 0]) # first element
print(x[-1, -1]) # last element
print(x[5, 7]) # 5 row and 7 column index
# row
print(x[0]) # first row
print(x[-1]) # last row

10
99
61
[10 10 11 12 13 14 15 16 17 18]
[90 91 92 93 94 95 96 97 98 99]


In [9]:
print(x[:, 0]) # first column
print(x[:, -1]) # last column

[10 18 27 36 45 54 63 72 81 90]
[18 27 36 45 54 63 72 81 90 99]


In [10]:
print(x[:, :3]) # first 3 column
print(x[:, -3:]) # last 3 column

[[10 10 11]
 [18 19 20]
 [27 28 29]
 [36 37 38]
 [45 46 47]
 [54 55 56]
 [63 64 65]
 [72 73 74]
 [81 82 83]
 [90 91 92]]
[[16 17 18]
 [25 26 27]
 [34 35 36]
 [43 44 45]
 [52 53 54]
 [61 62 63]
 [70 71 72]
 [79 80 81]
 [88 89 90]
 [97 98 99]]


In [11]:
print(x[:3, :5]) # first 3 row, and first 5 column

[[10 10 11 12 13]
 [18 19 20 21 22]
 [27 28 29 30 31]]
